---
# tasks file for virtualbox-guest
- block:
  - name: Remove os packages version of virtualbox guest additions
    package: name="{{ item }}" state="absent" purge="yes"
    with_items: "{{ virtualbox_os_packages }}"
  when: virtualbox_remove_os_packages is defined and virtualbox_remove_os_packages


- block:
  - name: If virtualbox_version is set to auto then determine the host version
    local_action: shell vboxmanage --version | awk -F'[r_]' '{print $1}'
    register: host_vbox_version
    become: no

  - name: Check if virtualbox_version could be determined
    fail: msg="Could not determine virtualbox_version - please specify this variable"
    when: host_vbox_version.stdout == ""

  - name: Override virtualbox_version if defaults set to auto
    set_fact: virtualbox_version="{{ host_vbox_version.stdout }}"
  when: virtualbox_version == "auto"

- name: Determine if (the requested version of) vboxguestadditions is installed
  shell: modinfo vboxguest 2>/dev/null|awk '/^version/{print $2}'
  register: vbox_guest_version
  changed_when: vbox_guest_version.stdout != virtualbox_version
  # ignore_errors: yes

- block:
  - name: Check if the ISO file is present on the host
    stat: path="{{ virtualbox_iso }}"
    ##stat: path=/root/VBoxGuestAdditions.iso
    register: file_path
    # ignore_errors: yes

  - name: Check if the CD is present on the host
    stat: path=/dev/sr0
    register: CD_path
    # ignore_errors: yes
    when: not file_path.stat.exists

  - name: Check if CD or ISO file is present on the host
    debug: msg="Could not find necessary CD or ISO file on the host. Attempting to download..."
    when: not file_path.stat.exists and not CD_path.stat.exists

  - name: Download ISO file when the requested version is not present on the host
    get_url: url=http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/VBoxGuestAdditions_{{ virtualbox_version }}.iso dest=/root/VBoxGuestAdditions.iso
    ## tried to fetch     http://download.virtualbox.org/virtualbox/4.3.36_Ubuntu/VBoxGuestAdditions_4.3.36_Ubuntu.iso
    ## but actual path is http://download.virtualbox.org/virtualbox/4.3.36/VBoxGuestAdditions_4.3.36.iso
    # ignore_errors: yes
    when: not file_path.stat.exists and not CD_path.stat.exists

  - name: Re-check if the ISO file is present on the host
    stat: path="{{ virtualbox_iso }}"
    register: file_path
    # ignore_errors: yes

  - debug:
      msg: "{{ virtualbox_iso }}"

  - debug:
      msg: "{{ file_path }}"

  - name: Fail if CD or ISO file is still not present on the host
    fail: msg="Could not find necessary CD or ISO file on the host."
    when: not file_path.stat.exists and not CD_path.stat.exists

  - name: Use correct ISO path (file or CD)
    set_fact: ISO_path="{{ file_path.stat.path if file_path.stat.exists else CD_path.stat.path }}"

  - name: Check if VBoxGuest additions ISO is mounted
    shell: mount -l 2>/dev/null|awk '/VBOXADDITIONS/{print $3}'
    register: mount_path
    changed_when: mount_path is defined and mount_path.stdout != ""

  - name: Mount VBoxGuestAdditions
    mount:
      name=/media/cdrom
      src={{ ISO_path }}
      fstype=iso9660
      opts=noauto,loop
      state=mounted
    register: mounted_ISO
    when: mount_path is defined and mount_path.stdout == ""

  - name: Check if VBoxGuest additions ISO is mounted
    shell: mount -l 2>/dev/null|awk 'tolower($0) ~ /vbox.*additions/{print $3}'
    register: mount_path

  - name: Find out kernel version
    shell: uname -r
    register: kernel
    changed_when: kernel.stdout == ""

  - name: Find out architecture-independent kernel name
    shell: uname -r | sed 's/-[az].*$//'
    register: kernel_common
    changed_when: kernel_common.stdout == ""

  - name: Save the current list of packages for Debians
    shell: dpkg-query -l > /tmp/before.txt
    when: ansible_os_family == 'Debian' and ( virtualbox_keep is undefined or not virtualbox_keep )

  - name: Save the current list of packages for CentOSes
    shell: rpm -qa > /tmp/before.txt
    when: ansible_os_family == 'RedHat' and ( virtualbox_keep is undefined or not virtualbox_keep )

  - block:
    - name: Install EPEL repo.
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: latest #present
        validate_certs: no
    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present
    when: ansible_os_family == 'RedHat'

  - name: Install necessary packages for compiling
    package:
      name: "{{ item }}"
      # update_cache=yes
      # install-recommends=no
      state: present
    with_items:
      - bzip2
      - dkms
      - gcc
      - make

  - name: Install kernel headers for Debians
    apt:
      name=linux-headers-{{ kernel.stdout }}
      update_cache=yes
      cache_valid_time=86400
      install-recommends=no
      state=present
    when: kernel is defined and kernel.stdout is defined and ansible_os_family == 'Debian'

  - name: Install libselinux-python for RedHat
    yum:
      name=libselinux-python
    when: ansible_os_family == 'RedHat'


  - name: Install latest kernel and headers for CentOSes
    yum:
      name: "{{ item }}"
      state: latest # needed latest for dmks to find matching header
      update_cache: yes
    with_items:
      - kernel
      - kernel-headers-{{ kernel.stdout }}
      - kernel-devel
    when: kernel is defined and ansible_os_family == 'RedHat' and kernel.stdout is defined

  - name: Check which packages were installed for Debians
    shell: dpkg-query -l > /tmp/after.txt
    when: ansible_os_family == 'Debian' and ( virtualbox_keep is undefined or not virtualbox_keep )

  - name: Check which packages were installed for CentOSes
    shell: rpm -qa > /tmp/after.txt
    when: ansible_os_family == 'RedHat' and ( virtualbox_keep is undefined or not virtualbox_keep )

  - name: Create a list of installed packages
    shell: diff /tmp/before.txt /tmp/after.txt|awk '/>/{print $3}'
    register: installed
    when: virtualbox_keep is undefined or not virtualbox_keep

  - name: Build and install x11 VBoxGuestAdditions from file
    shell: /bin/bash /media/cdrom/VBoxLinuxAdditions.run
    when: virtualbox_x11 is defined and virtualbox_x11
    # ignore_errors: yes

  - name: Build and install VBoxGuestAdditions from file for Debians
    shell: /bin/bash /media/cdrom/VBoxLinuxAdditions.run --nox11
    when: ( virtualbox_x11 is undefined or not virtualbox_x11 ) and ansible_os_family == 'Debian'
    # ignore_errors: yes

  - name: Build and install VBoxGuestAdditions from file for CentOSes
    shell: /bin/bash  /media/cdrom/VBoxLinuxAdditions.run --nox11
    when: ( virtualbox_x11 is undefined or not virtualbox_x11 ) and ansible_os_family == 'RedHat'
    # ignore_errors: yes

  - name: Unmount VBoxGuestAdditions
    mount:
      name={{ mount_path.stdout }}
      src={{ ISO_path }}
      fstype=iso9660
      state=unmounted
    when: mounted_ISO | changed

  - name: Remove installed packages for compiling
    package:
      name: "{{ installed.stdout_lines }}"
      state: absent
      #update_cache=yes
      #cache_valid_time=86400
      #autoremove=yes
      #purge=yes
    when: installed is defined and (virtualbox_keep is undefined or not virtualbox_keep)

  - name: Remove build logfiles, artefacts and ISO files
    file: name={{ item}} follow=yes state=absent
    with_items:
      - "/opt/VBoxGuestAdditions-{{ virtualbox_version }}/src"
      - /root/VBoxGuestAdditions.iso
      - /tmp/before.txt
      - /tmp/after.txt
      - "/usr/src/vboxguest-{{ virtualbox_version }}"
      - /var/lib/dkms/vboxguest
      - /var/log/vboxadd-install.log
      - /var/log/vboxadd-install-x11.log
      - /var/log/VBoxGuestAdditions.log
      - /var/log/VBoxGuestAdditions-uninstall.log

  - name: Remove cdrom fstab entry
    lineinfile: >
      dest=/etc/fstab
      regexp='^{{ ISO_path }}'
      line='{{ ISO_path }}	{{ mount_path.stdout }}	iso9660	noauto	0	0'
      state=absent
    when: mounted_ISO | changed
  when: (vbox_guest_version.stdout != virtualbox_version)
